version: '3.9'
name: template-microservice
services:
  books:
    build:
      context: ../../books/
      dockerfile: ./deployment/Dockerfile
    container_name: "books"
    expose:
      - "80"
    networks:
      - back

  gateway:
    build:
      context: ../../gateway/
      dockerfile: ./deployment/Dockerfile
    container_name: "gateway"
    ports:
      - "8001:8000"
    networks:
      - front
      - back
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=gateproj.settings
      - DJANGO_LOG_LEVEL=DEBUG
      - BOOKS_HOST=http://books:80
    depends_on:
      books:
        condition: service_started

  frontend:
    build:
      context: ../../front/
      dockerfile: ./deployment/Dockerfile
    container_name: "frontend"
    ports:
      - "8000:8000"
    networks:
      - front
      - back
    environment:
      - HOST=http://localhost:8000
      - API_HOST=http://gateway:8001

    depends_on:
      gateway:
        condition: service_started

networks:
  front:
    driver: bridge
    name: template_microservice_front
  back:
    driver: bridge
    internal: true
    name: template_microservice_back
